import test from 'node:test'
import assert from 'node:assert/strict'

import {
  createAffiliateLinkProvider,
  createPlaywrightAffiliateSession,
} from '../../src/bot/providers/affiliate-link-provider.js'

test('affiliate provider returns the short affiliate link generated by the authenticated session', async () => {
  const calls = []
  let closed = false

  const provider = createAffiliateLinkProvider({
    tag: 'rm20250209133551',
    createAffiliateSession: async () => ({
      async createLink(payload) {
        calls.push(payload)

        return {
          urls: [
            {
              short_url: 'https://meli.la/2Bq2Xkp',
              long_url: 'https://www.mercadolivre.com.br/social/test?ref=abc',
            },
          ],
        }
      },
      async close() {
        closed = true
      },
    }),
  })

  const affiliateLink = await provider.getAffiliateLink({
    id: 'MLB6204289',
    permalink: 'https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289',
  })

  assert.deepEqual(affiliateLink, {
    url: 'https://meli.la/2Bq2Xkp',
    source: 'affiliate',
    usedFallback: false,
  })
  assert.deepEqual(calls, [
    {
      urls: ['https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289'],
      tag: 'rm20250209133551',
    },
  ])

  await provider.close()
  assert.equal(closed, true)
})

test('affiliate provider can return the long affiliate link when configured', async () => {
  const provider = createAffiliateLinkProvider({
    tag: 'rm20250209133551',
    linkFormat: 'long',
    createAffiliateSession: async () => ({
      async createLink() {
        return {
          urls: [
            {
              short_url: 'https://meli.la/2Bq2Xkp',
              long_url: 'https://www.mercadolivre.com.br/social/test?ref=abc',
            },
          ],
        }
      },
      async close() {},
    }),
  })

  const affiliateLink = await provider.getAffiliateLink({
    id: 'MLB6204289',
    permalink: 'https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289',
  })

  assert.deepEqual(affiliateLink, {
    url: 'https://www.mercadolivre.com.br/social/test?ref=abc',
    source: 'affiliate',
    usedFallback: false,
  })
})

test('affiliate provider requires a tag when template mode is disabled', async () => {
  const provider = createAffiliateLinkProvider({
    tag: '',
    createAffiliateSession: async () => ({
      async createLink() {
        throw new Error('should not reach session creation')
      },
      async close() {},
    }),
  })

  await assert.rejects(
    () =>
      provider.getAffiliateLink({
        id: 'MLB6204289',
        permalink: 'https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289',
      }),
    /ML_AFFILIATE_TAG/,
  )
})

test('affiliate provider sanitizes the configured tag before calling Mercado Livre', async () => {
  const calls = []

  const provider = createAffiliateLinkProvider({
    tag: 'rm20250209133551. ',
    createAffiliateSession: async () => ({
      async createLink(payload) {
        calls.push(payload)

        return {
          urls: [
            {
              short_url: 'https://meli.la/2Bq2Xkp',
            },
          ],
        }
      },
      async close() {},
    }),
  })

  const affiliateLink = await provider.getAffiliateLink({
    id: 'MLB6204289',
    permalink: 'https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289',
  })

  assert.deepEqual(affiliateLink, {
    url: 'https://meli.la/2Bq2Xkp',
    source: 'affiliate',
    usedFallback: false,
  })
  assert.deepEqual(calls, [
    {
      urls: ['https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289'],
      tag: 'rm20250209133551',
    },
  ])
})

test('playwright affiliate session prefers the saved profile directory over storage state when both are configured', async () => {
  const persistentCalls = []
  let contextClosed = false

  const session = await createPlaywrightAffiliateSession({
    storageStatePath: 'sessions/affiliate-storage-state.json',
    userDataDir: 'sessions/affiliate-profile',
    playwrightModule: {
      chromium: {
        async launch() {
          throw new Error('storage state should not be used first')
        },
        async launchPersistentContext(userDataDir, options) {
          persistentCalls.push({ userDataDir, options })

          return {
            pages() {
              return [{
                setDefaultTimeout() {},
                async goto() {},
                async waitForLoadState() {},
                url() {
                  return 'https://www.mercadolivre.com.br/afiliados/linkbuilder#hub'
                },
                async evaluate() {
                  return {
                    status: 200,
                    body: JSON.stringify({
                      urls: [{ short_url: 'https://meli.la/teste' }],
                    }),
                  }
                },
              }]
            },
            async close() {
              contextClosed = true
            },
            async storageState() {},
          }
        },
      },
    },
  })

  const payload = await session.createLink({
    urls: ['https://www.mercadolivre.com.br/p/produto'],
    tag: 'rm20250209133551',
  })

  assert.equal(persistentCalls.length, 1)
  assert.equal(persistentCalls[0].userDataDir, 'sessions/affiliate-profile')
  assert.deepEqual(persistentCalls[0].options.args, [
    '--no-sandbox',
    '--disable-setuid-sandbox',
    '--disable-dev-shm-usage',
    '--no-first-run',
    '--no-default-browser-check',
  ])
  assert.equal(payload.urls[0].short_url, 'https://meli.la/teste')

  await session.close()
  assert.equal(contextClosed, true)
})

test('affiliate provider retries with the saved profile when the storage state is expired and refreshes it', async () => {
  const calls = []
  const savedStates = []
  let sessionAttempts = 0

  const provider = createAffiliateLinkProvider({
    tag: 'rm20250209133551',
    storageStatePath: 'sessions/affiliate-storage-state.json',
    userDataDir: 'sessions/affiliate-profile',
    createAffiliateSession: async ({ storageStatePath, userDataDir }) => {
      sessionAttempts += 1

      if (sessionAttempts === 1) {
        assert.equal(storageStatePath, 'sessions/affiliate-storage-state.json')

        return {
          async createLink() {
            throw new Error('Mercado Livre affiliate session expired or is not authorized.')
          },
          async close() {},
        }
      }

      assert.equal(userDataDir, 'sessions/affiliate-profile')

      return {
        async createLink(payload) {
          calls.push(payload)

          return {
            urls: [
              {
                short_url: 'https://meli.la/novo-link',
              },
            ],
          }
        },
        async saveStorageState(path) {
          savedStates.push(path)
        },
        async close() {},
      }
    },
  })

  const affiliateLink = await provider.getAffiliateLink({
    id: 'MLB6204289',
    permalink: 'https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289',
  })

  assert.deepEqual(affiliateLink, {
    url: 'https://meli.la/novo-link',
    source: 'affiliate',
    usedFallback: false,
  })
  assert.equal(sessionAttempts, 2)
  assert.deepEqual(savedStates, ['sessions/affiliate-storage-state.json'])
  assert.deepEqual(calls, [
    {
      urls: ['https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289'],
      tag: 'rm20250209133551',
    },
  ])
})

test('affiliate provider falls back to the configured template when affiliate authentication stays expired', async () => {
  let sessionAttempts = 0

  const provider = createAffiliateLinkProvider({
    tag: 'rm20250209133551',
    templateUrl: 'https://www.mercadolivre.com.br/social/test?url={{url}}&id={{id}}',
    storageStatePath: 'sessions/affiliate-storage-state.json',
    userDataDir: 'sessions/affiliate-profile',
    createAffiliateSession: async () => {
      sessionAttempts += 1

      return {
        async createLink() {
          throw new Error('Mercado Livre affiliate session expired or is not authorized.')
        },
        async close() {},
      }
    },
  })

  const affiliateLink = await provider.getAffiliateLink({
    id: 'MLB6204289',
    permalink: 'https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289',
  })

  assert.deepEqual(affiliateLink, {
    url: 'https://www.mercadolivre.com.br/social/test?url=https%3A%2F%2Fwww.mercadolivre.com.br%2Fcreatina-100-pura-300g-integralmedica%2Fp%2FMLB6204289&id=MLB6204289',
    source: 'template',
    usedFallback: true,
  })
  assert.equal(sessionAttempts, 2)
})

test('affiliate provider falls back to the permalink when affiliate authentication stays expired and no template fallback exists', async () => {
  let sessionAttempts = 0

  const provider = createAffiliateLinkProvider({
    tag: 'rm20250209133551',
    storageStatePath: 'sessions/affiliate-storage-state.json',
    userDataDir: 'sessions/affiliate-profile',
    createAffiliateSession: async () => {
      sessionAttempts += 1

      return {
        async createLink() {
          throw new Error('Mercado Livre affiliate session expired or is not authorized.')
        },
        async close() {},
      }
    },
  })

  const affiliateLink = await provider.getAffiliateLink({
    id: 'MLB6204289',
    permalink: 'https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289',
  })

  assert.deepEqual(affiliateLink, {
    url: 'https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289',
    source: 'permalink',
    usedFallback: true,
    fallbackReason: 'affiliate_reauth_required',
  })
  assert.equal(sessionAttempts, 2)
})

test('affiliate provider recreates the session when Playwright closes the browser unexpectedly', async () => {
  let sessionAttempts = 0

  const provider = createAffiliateLinkProvider({
    tag: 'rm20250209133551',
    createAffiliateSession: async () => {
      sessionAttempts += 1

      if (sessionAttempts === 1) {
        return {
          async createLink() {
            throw new Error('page.goto: Target page, context or browser has been closed')
          },
          async close() {},
        }
      }

      return {
        async createLink() {
          return {
            urls: [
              {
                short_url: 'https://meli.la/recovered',
              },
            ],
          }
        },
        async close() {},
      }
    },
  })

  const affiliateLink = await provider.getAffiliateLink({
    id: 'MLB6204289',
    permalink: 'https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289',
  })

  assert.deepEqual(affiliateLink, {
    url: 'https://meli.la/recovered',
    source: 'affiliate',
    usedFallback: false,
  })
  assert.equal(sessionAttempts, 2)
})

test('affiliate provider recreates the session when Playwright fails during session bootstrap', async () => {
  let sessionAttempts = 0

  const provider = createAffiliateLinkProvider({
    tag: 'rm20250209133551',
    createAffiliateSession: async () => {
      sessionAttempts += 1

      if (sessionAttempts === 1) {
        throw new Error('browserType.launchPersistentContext: Target page, context or browser has been closed')
      }

      return {
        async createLink() {
          return {
            urls: [
              {
                short_url: 'https://meli.la/bootstrap-ok',
              },
            ],
          }
        },
        async close() {},
      }
    },
  })

  const affiliateLink = await provider.getAffiliateLink({
    id: 'MLB6204289',
    permalink: 'https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289',
  })

  assert.deepEqual(affiliateLink, {
    url: 'https://meli.la/bootstrap-ok',
    source: 'affiliate',
    usedFallback: false,
  })
  assert.equal(sessionAttempts, 2)
})
