import test from 'node:test'
import assert from 'node:assert/strict'

import { createAffiliateLinkProvider } from '../../src/bot/providers/affiliate-link-provider.js'

test('affiliate provider returns the short affiliate link generated by the authenticated session', async () => {
  const calls = []
  let closed = false

  const provider = createAffiliateLinkProvider({
    tag: 'rm20250209133551',
    createAffiliateSession: async () => ({
      async createLink(payload) {
        calls.push(payload)

        return {
          urls: [
            {
              short_url: 'https://meli.la/2Bq2Xkp',
              long_url: 'https://www.mercadolivre.com.br/social/test?ref=abc',
            },
          ],
        }
      },
      async close() {
        closed = true
      },
    }),
  })

  const affiliateLink = await provider.getAffiliateLink({
    id: 'MLB6204289',
    permalink: 'https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289',
  })

  assert.equal(affiliateLink, 'https://meli.la/2Bq2Xkp')
  assert.deepEqual(calls, [
    {
      urls: ['https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289'],
      tag: 'rm20250209133551',
    },
  ])

  await provider.close()
  assert.equal(closed, true)
})

test('affiliate provider can return the long affiliate link when configured', async () => {
  const provider = createAffiliateLinkProvider({
    tag: 'rm20250209133551',
    linkFormat: 'long',
    createAffiliateSession: async () => ({
      async createLink() {
        return {
          urls: [
            {
              short_url: 'https://meli.la/2Bq2Xkp',
              long_url: 'https://www.mercadolivre.com.br/social/test?ref=abc',
            },
          ],
        }
      },
      async close() {},
    }),
  })

  const affiliateLink = await provider.getAffiliateLink({
    id: 'MLB6204289',
    permalink: 'https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289',
  })

  assert.equal(affiliateLink, 'https://www.mercadolivre.com.br/social/test?ref=abc')
})

test('affiliate provider requires a tag when template mode is disabled', async () => {
  const provider = createAffiliateLinkProvider({
    tag: '',
    createAffiliateSession: async () => ({
      async createLink() {
        throw new Error('should not reach session creation')
      },
      async close() {},
    }),
  })

  await assert.rejects(
    () =>
      provider.getAffiliateLink({
        id: 'MLB6204289',
        permalink: 'https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289',
      }),
    /ML_AFFILIATE_TAG/,
  )
})

test('affiliate provider sanitizes the configured tag before calling Mercado Livre', async () => {
  const calls = []

  const provider = createAffiliateLinkProvider({
    tag: 'rm20250209133551. ',
    createAffiliateSession: async () => ({
      async createLink(payload) {
        calls.push(payload)

        return {
          urls: [
            {
              short_url: 'https://meli.la/2Bq2Xkp',
            },
          ],
        }
      },
      async close() {},
    }),
  })

  const affiliateLink = await provider.getAffiliateLink({
    id: 'MLB6204289',
    permalink: 'https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289',
  })

  assert.equal(affiliateLink, 'https://meli.la/2Bq2Xkp')
  assert.deepEqual(calls, [
    {
      urls: ['https://www.mercadolivre.com.br/creatina-100-pura-300g-integralmedica/p/MLB6204289'],
      tag: 'rm20250209133551',
    },
  ])
})
